version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      - "MINIO_ROOT_USER=user"
      - "MINIO_ROOT_PASSWORD=password"
    command: server /data --console-address :9001 # startup command
  
  createbucket:
    image: minio/mc:latest # mc image is used for executing minio commands
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio-s3 http://minio:9000 user password;
      /usr/bin/mc mb minio-s3/datalake/;
      /usr/bin/mc anonymous set public minio-s3/datalake;
      exit 0;
      "
